#!/bin/bash
set -e

# ============================================
# MORVO TempMail - Backup Script
# ============================================
# Creates a tarball of app code + data + configs
# Run on OLD VPS, then transfer tarball to NEW VPS
#
# Usage: bash deploy/backup.sh [--include-ssl]

APP_DIR="/var/www/morvo-tempmail"
BACKUP_DIR="/tmp/morvo-backup-$(date +%Y%m%d_%H%M%S)"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
OUTPUT="/tmp/morvo-full-backup-${TIMESTAMP}.tar.gz"

GREEN='\033[0;32m'
NC='\033[0m'
log() { echo -e "${GREEN}[✓]${NC} $1"; }

echo "📦 MORVO TempMail - Creating Backup"
echo "===================================="

mkdir -p "$BACKUP_DIR"

# 1. Application source code
log "Copying application code..."
cp -r "$APP_DIR/src" "$BACKUP_DIR/"
cp -r "$APP_DIR/public" "$BACKUP_DIR/"
cp -r "$APP_DIR/api" "$BACKUP_DIR/"
cp -r "$APP_DIR/scripts" "$BACKUP_DIR/"
cp -r "$APP_DIR/test" "$BACKUP_DIR/"
cp -r "$APP_DIR/deploy" "$BACKUP_DIR/"
cp "$APP_DIR/package.json" "$BACKUP_DIR/"
cp "$APP_DIR/package-lock.json" "$BACKUP_DIR/"
cp "$APP_DIR/.gitignore" "$BACKUP_DIR/"
cp "$APP_DIR/.npmrc" "$BACKUP_DIR/"
cp "$APP_DIR/vercel.json" "$BACKUP_DIR/"
cp "$APP_DIR/ecosystem.config.js" "$BACKUP_DIR/"
cp "$APP_DIR/README.md" "$BACKUP_DIR/"

# 2. Database (critical!)
log "Copying database..."
cp -r "$APP_DIR/data" "$BACKUP_DIR/"

# 3. Nginx config
log "Copying Nginx config..."
mkdir -p "$BACKUP_DIR/etc-nginx"
cp /etc/nginx/sites-available/morvo-tempmail "$BACKUP_DIR/etc-nginx/" 2>/dev/null || warn "Nginx config not found"

# 4. PM2 ecosystem (already copied above)

# 5. Environment info
log "Saving environment info..."
cat > "$BACKUP_DIR/env-info.txt" << 'ENVEOF'
# MORVO TempMail - Environment Info
# Generated by backup.sh
# Use this to verify setup on new VPS

Node version required: 22.x
NPM version: 10.x
OS: Ubuntu 22.04+ (x86_64)

# Required npm packages (installed from package.json):
#   express, bcryptjs, cookie-parser, express-session, mailparser, smtp-server

# Required system packages:
#   nginx, certbot, python3-certbot-nginx, nodejs, pm2

# Ports used:
#   25  - SMTP inbound (receiving emails)
#   80  - HTTP (Nginx redirect to HTTPS)
#   443 - HTTPS (Nginx reverse proxy -> Node.js :3000)
#   3000 - Node.js app (internal, proxied by Nginx)

# DNS records needed:
#   morvo.me          A      -> YOUR_SERVER_IP
#   www.morvo.me      A      -> YOUR_SERVER_IP
#   morvo.me          MX     -> 10 mail.morvo.me
#   mail.morvo.me         A   -> YOUR_SERVER_IP
ENVEOF

# 6. Git history
log "Copying git history..."
cp -r "$APP_DIR/.git" "$BACKUP_DIR/" 2>/dev/null || true

# Create tarball
log "Creating tarball..."
cd /tmp
tar -czf "$OUTPUT" "$(basename $BACKUP_DIR)"

# Cleanup
rm -rf "$BACKUP_DIR"

echo ""
echo "===================================="
echo "✅ Backup complete!"
echo "📁 File: $OUTPUT"
echo "📊 Size: $(du -h "$OUTPUT" | cut -f1)"
echo ""
echo "Transfer to new VPS:"
echo "  scp $OUTPUT root@NEW_VPS_IP:/tmp/"
echo ""
echo "Then on new VPS:"
echo "  mkdir -p /var/www/morvo-tempmail"
echo "  cd /var/www"
echo "  tar -xzf /tmp/morvo-full-backup-*.tar.gz --strip-components=1 -C /var/www/morvo-tempmail"
echo "  bash /var/www/morvo-tempmail/deploy/setup.sh"
echo "===================================="
